name: Send Inactive Emails

on:
  schedule:
    # - cron: '0 */2 * * *'
    - cron: '*/3 * * * *' 

  workflow_dispatch:

jobs:
  send-emails:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          node-version: '20'

      - run: npm install

      - run: node scripts/sendEmails.js
        env:
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          BREVO_SMTP_SERVER: ${{ secrets.BREVO_SMTP_SERVER }}
          BREVO_SMTP_PORT: ${{ secrets.BREVO_SMTP_PORT }}
          BREVO_SMTP_LOGIN: ${{ secrets.BREVO_SMTP_LOGIN }}
          BREVO_SMTP_PASSWORD: ${{ secrets.BREVO_SMTP_PASSWORD }}